version: '3'
services:

  db:
    container_name: db_prod

  api:
    container_name: api_prod
    image: ghcr.io/divselector/webchain-api:latest

  rabbitmq:
    container_name: rabbitmq_prod

  nginx:
    container_name: nginx_prod
    image: ghcr.io/divselector/webchain-nginx:latest
    build:
      dockerfile: ./nginx/Dockerfile.production
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      - static_files:/usr/share/nginx/django
      - ./nginx/build:/usr/share/nginx/react
      - /etc/letsencrypt/live/neorings.org:/etc/letsencrypt/live/neorings.org:ro
    environment:
      - ENVIRONMENT=production
    depends_on:
      - api
