version: '3'
services:

  nginx:
    container_name: nginx
    build:
      dockerfile: ./nginx/Dockerfile.production
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      - static_files:/usr/share/nginx/django
      - ./nginx/build:/usr/share/nginx/react
      - ./certbot/www/:/var/www/certbot/:ro
    environment:
      - ENVIRONMENT=production
    depends_on:
      - api

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw