version: '3'
services:

  nginx:
    container_name: nginx
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - static_files:/usr/share/nginx/django
      - ./nginx/build:/usr/share/nginx/react
    depends_on:
      - api


  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - ~/srv/docker/template-postgres/data:/var/lib/postgresql/data:rw

  api:
    build:
      dockerfile: ./back/Dockerfile
    container_name: api
    volumes:
      - static_files:/src/back/staticfiles/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - rabbitmq


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "1${RABBITMQ_PORT}:1${RABBITMQ_PORT}"


volumes:
  static_files:
