# Generated by Django 4.2.2 on 2023-06-15 08:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import webrings.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('date_created', models.DateTimeField(auto_now_add=True, validators=[webrings.validators.validate_date_not_in_future])),
                ('date_updated', models.DateTimeField(auto_now=True, validators=[webrings.validators.validate_date_not_in_future])),
                ('primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, validators=[webrings.validators.validate_date_not_in_future])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, validators=[webrings.validators.validate_date_not_in_future])),
                ('date_updated', models.DateTimeField(auto_now=True, validators=[webrings.validators.validate_date_not_in_future])),
                ('automatic_approval', models.BooleanField(default=False)),
                ('primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebringPageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webring_page_links_from_page', to='webrings.page')),
                ('webring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webring_page_links_from_webring', to='webrings.webring')),
            ],
        ),
        migrations.AddField(
            model_name='webring',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='webrings_from_page', through='webrings.WebringPageLink', to='webrings.page'),
        ),
        migrations.AddField(
            model_name='webring',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webrings_from_profile', to='webrings.profile'),
        ),
        migrations.AddField(
            model_name='page',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_from_profile', to='webrings.profile'),
        ),
        migrations.AddField(
            model_name='page',
            name='webrings',
            field=models.ManyToManyField(blank=True, related_name='pages_from_webrings', through='webrings.WebringPageLink', to='webrings.webring'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('free', 'Free'), ('subscriber', 'Subscriber')], default='free', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
