# Generated by Django 4.2.2 on 2023-06-15 13:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import webrings.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('account_type', models.CharField(choices=[('free', 'Free'), ('subscriber', 'Subscriber')], default='free', max_length=12)),
                ('date_updated', models.DateTimeField(auto_now=True, validators=[webrings.validators.validate_date_not_in_future])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True, validators=[webrings.validators.validate_date_not_in_future])),
                ('date_updated', models.DateTimeField(auto_now=True, validators=[webrings.validators.validate_date_not_in_future])),
                ('automatic_approval', models.BooleanField(default=False)),
                ('primary', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_from_webring', related_query_name='account', to='webrings.account')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('date_created', models.DateTimeField(auto_now_add=True, validators=[webrings.validators.validate_date_not_in_future])),
                ('date_updated', models.DateTimeField(auto_now=True, validators=[webrings.validators.validate_date_not_in_future])),
                ('primary', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_from_page', related_query_name='account', to='webrings.account')),
                ('webrings', models.ManyToManyField(blank=True, related_name='pages', related_query_name='page', to='webrings.webring')),
            ],
        ),
    ]
