# Generated by Django 4.2.2 on 2023-07-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('free', 'Free'), ('subscriber', 'Subscriber')], default='free', max_length=12),
        ),
    ]
