# Generated by Django 4.2.2 on 2023-08-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrings', '0002_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='webring',
            name='title',
            field=models.CharField(max_length=42),
        ),
    ]
