FROM nginx:latest

RUN mkdir -p /usr/share/nginx/react
RUN mkdir -p /etc/nginx/ssl/live/neorings.org/

COPY ./nginx/build/* /usr/share/nginx/react
COPY ./nginx/html/* /usr/share/nginx/html
COPY ./nginx/include/* /etc/nginx

COPY ./nginx/ssl/letsencrypt /etc/nginx/ssl/live/neorings.org/

WORKDIR /etc/nginx/
